### DISCUSSION TITLE
GPRC TLS Traefik Let's encrypt

### DISCUSSION THREAD

**Discussion by PaoloC68** [uptrace/uptrace#166] [Q&A]
Hi,
can anybody point me to some documentation or examples to achieve the same configuration of the GPRC endpoints that you have for the cloud version?

I would like to achieve (if possible) the following:

- Have that http://my_secret@uptrace.mydomain.com:14317/3 will become https://my_secret@grpc-uptrace.mydomain.com/3 using Traefik reverse proxy and Let's encrypt released certificates
- Have that http://uptrace.mydomain.com:4317 becomes https://otel-gprc.mydomain.com in the same mentioned context above.
In general I would like to understand if the certificates released by Let's encrypt could be used to encrypt the Uptrace gprc connection.
Thanks in advance!

This is my current docker compose configuration:

```
version: '3'

networks:
  internal:
  traefik-monitoring:
    external: true
services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.7
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ch_data_2:/var/lib/clickhouse
    ports:
      - '8123'
      - '9000'
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=false
    networks:
      - internal

  uptrace:
    image: 'uptrace/uptrace:1.3.0'
    #image: 'uptrace/uptrace-dev:latest'
    restart: on-failure
    volumes:
      - uptrace_data:/var/lib/uptrace
      - ./uptrace.yml:/etc/uptrace/uptrace.yml
    #environment:
    #  - DEBUG=2
    ports:
      - '14317:14317'
      - '14318:14318'
    depends_on:
      - clickhouse
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-monitoring
        - traefik.constraint-label=traefik-public

        - traefik.http.routers.uptrace.rule=Host(`uptrace.mydomain.com`)
        - traefik.http.routers.uptrace.entrypoints=websecure
        - traefik.http.routers.uptrace.tls=true
        - traefik.http.routers.uptrace.tls.certresolver=leresolver
        - traefik.http.services.uptrace.loadbalancer.server.port=14318
        - traefik.http.routers.uptrace.service=uptrace

        - traefik.http.routers.grpcuptrace.rule=Host(`grpc-uptrace.mydomain.com`)
        - traefik.http.routers.grpcuptrace.entrypoints=websecure
        - traefik.http.routers.grpcuptrace.tls=true
        - traefik.http.routers.grpcuptrace.tls.certresolver=leresolver
        - traefik.http.services.grpcuptrace.loadbalancer.server.scheme=h2c
        - traefik.http.services.grpcuptrace.loadbalancer.server.port=14317
        - traefik.http.routers.grpcuptrace.service=uptrace

    networks:
      - internal
      - traefik-monitoring

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.70.0
    restart: on-failure
    user: '0:0' # required for logs
    volumes:
      - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    ports:
      - '4317:4317'
      - '4318:4318'
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-monitoring
        - traefik.constraint-label=traefik-public

        - traefik.http.routers.otel.rule=Host(`otel.mydomain.com`)
        - traefik.http.routers.otel.entrypoints=websecure
        - traefik.http.routers.otel.tls=true
        - traefik.http.routers.otel.tls.certresolver=leresolver
        - traefik.http.services.otel.loadbalancer.server.port=4318
        - traefik.http.routers.otel.service=otel

        - traefik.http.routers.grpc.rule=Host(`grpc.mydomain.com`)
        - traefik.http.routers.grpc.entrypoints=websecure
        - traefik.http.routers.grpc.tls=true
        - traefik.http.routers.grpc.tls.certresolver=leresolver
        - traefik.http.services.grpc.loadbalancer.server.scheme=h2c
        - traefik.http.services.grpc.loadbalancer.server.port=4317
        - traefik.http.routers.grpc.service=otel

    networks:
      - internal
      - traefik-monitoring


  alertmanager:
    image: prom/alertmanager:v0.24.0
    restart: on-failure
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/config.yml
      - alertmanager_data:/alertmanager
    ports:
      - '9093'
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=false
    networks:
      - internal
  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: on-failure
    ports:
      - '8025'
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=false
    networks:
      - internal

  vector:
    image: timberio/vector:0.24.X-alpine
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=false
    networks:
      - internal

  # jaeger-agent:
  #   image: jaegertracing/jaeger-agent:latest
  #   command: ['--reporter.grpc.host-port=localhost:14250']
  #   network_mode: host

  # jaeger-hot-rod:
  #   image: jaegertracing/example-hotrod:latest
  #   command: ['all']
  #   network_mode: host
  #   environment:
  #     - JAEGER_AGENT_HOST=localhost
  #     - JAEGER_AGENT_PORT=6831
  #   depends_on:
  #     - jaeger-agent

volumes:
  uptrace_data:
    driver: local
  ch_data_2:
    driver: local
  alertmanager_data:
    driver: local
```
