### ISSUE TITLE
Error parsing metrics from otel-collector prometheus receiver

### ISSUE THREAD

**Issue by GinkT** [uptrace/uptrace#106]
Trying to collect prometheus metrics with otel-collector and pass them to uptrace.
Using prometheus_simple receiver and otlp exporter.

```
receivers:
  prometheus_simple:
    collection_interval: 10s
    endpoint: "host:port"
    metrics_path: "/metrics"
    tls_enabled: true
    tls:
      insecure_skip_verify: true

processors:
  resourcedetection:
    detectors: [system,env,docker]
  batch:
    send_batch_size: 10000
    timeout: 10s

exporters:
  otlp:
    endpoint: *endpoint*
    tls:
      insecure: true
    headers:
      uptrace-dsn: *dsn*

service:
  pipelines:
    metrics/prometheus_simple:
      receivers: [prometheus_simple]
      processors: [batch, resourcedetection]
      exporters: [otlp,logging]
```

But Uptrace logs an error for this pipeline.
```
uptrace_1       | 2022-09-29T16:02:41.300Z      error   metrics/otlp.go:203     unknown metric  {"type": "*v1.Metric_Summary"}
```
