### ISSUE TITLE
Add some templating capabilities to AlertManager templates

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/uptrace#125]
For https://github.com/uptrace/uptrace/issues/104

After v1.2.0 is released, we will have attributes and metrics values as the data in alerts, for example:

```json
{
    "rule": "$goroutines >= 0 group by host.name, service.name",
    "attrs": {"host.name": "localhost", "service.name": "myservice"}
    "metrics": {"$goroutines": 28},
}
```

The goal is to allow users to customize alerts, for example, to get a message like `$goroutines (28) is >= 100 on host.name=localhost service.name=myservice` we could have a template like `$goroutines ({{ $.Metrics["$goroutines"] }}) is >= 100 on {{ $.Attrs }}`.

In AlertManager, they have examples like [this](https://prometheus.io/docs/alerting/latest/notification_examples/#accessing-annotations-in-commonannotations):

```yaml
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
      summary: 'Instance {{ $labels.instance }} down'
```

So it looks like Uptrace should support templating in rules `annotations`. I guess it makes sense to use the same variable names as Prometheus/AlertManager.

The entry point to the relevant code is [here](https://github.com/uptrace/uptrace/blob/master/pkg/metrics/alerting.go#L154-L156).
