### ISSUE TITLE
[question] Alerts and "at least on project is required "

### ISSUE THREAD

**Issue by GriefNorth** [uptrace/uptrace#133]
When creating a rule for notifications, I get the error "at least on project is required"
```
error   uptrace/main.go:364     rule.Validate failed    {"error": "invalid rule \"Some test rule\": at least on project is required"}
```
What does this mean ?
My rule looks like this
```
    - name: Some test rule
      metrics:
        - uptrace.spans.duration as $duration 
      query:
        - group by span.group_id
        - where span.name = "SOME_APP_RPC"
        - p50(duration) > 100ms
      for: 1m
      project: [4]
```
