### ISSUE TITLE
[question] Alert rule doesn't work 

### ISSUE THREAD

**Issue by GriefNorth** [uptrace/uptrace#134]
Hello. I have configured custom metrics from a span
```
  - name: uptrace.tracing.spans_duration
    description: Spans duration (excluding events)
    instrument: histogram
    unit: microseconds
    value: span.duration / 1000
    attrs:
      - span.system as system
      - service.name as service
      - host.name as host
      - span.status_code as status
      - span.name as span_name
    where: not span.is_event      
```
and alert rule:
```
  - name: Duration of RPC more than 1min 
    metrics:
      - uptrace.tracing.spans_duration as $spans_duration
    query:
      - $spans_duration > 10s group by $spans_duration.span_name
    for: 2m
    projects: [4]
    annotations:
      summary: "Duration span {{ $labels.span_name }} = {{ $values.spans_duration }}"
```
but it doesn't work. 
However, the dashboards shows that one of the spans exceeds 10 seconds
![uptrace_dash](https://user-images.githubusercontent.com/2506351/203863624-402e05de-654c-40e6-80d9-4ef23c4a47a2.png)
What is wrong with the alert rule. Thanks so much for the help!

**Comment by vmihailenco** [comment]
@GriefNorth could you try to change `for: 2m` to `for: 1m`? It looks like the value is "flickering", i.e. every other minute the value is 0 so the condition `for 2 minutes` is never true.

I will release Uptrace v1.2.3 that should fix the problem with "flickering".

**Comment by GriefNorth** [comment]
I already tried and 0 1 minutes and 5

**Comment by vmihailenco** [comment]
This should be fixed in v1.2.4.

I recommend to change the metric to:

```
  - name: uptrace.tracing.spans_duration
    description: Spans duration (excluding events)
    instrument: histogram
    unit: microseconds
    value: span.duration / 1000
    attrs:
      - span.system as system
      - span.group_id as group_id
      - service.name as service
      - host.name as host
      - span.status_code as status
    annotations:
      - span.name
    where: not span.is_event
```

And the rule to:

```
  - name: Duration of RPC more than 1min 
    metrics:
      - uptrace.tracing.spans_duration as $spans_duration
    query:
      - $spans_duration > 10s group by span_name
    for: 2m
    projects: [4]
    annotations:
      summary: "Duration span {{ $annotations.span_name }} = {{ $values.spans_duration }}"
```

@GriefNorth could you try again?

**Comment by GriefNorth** [comment]
The problem was solved on version 1.2.4 with this rule for notifications
```
    - name: Duration of RPC more than 1min 
      metrics:
        - uptrace.tracing.spans_duration as $spans_duration
      query:
        - p50($spans_duration) > 60s group by group_id
      for: 1m
      projects: [4]
      annotations:
        summary: "Duration span {{ $annotations.span_name }} = {{ $values.spans_duration }}"
```
