### ISSUE TITLE
Allow to configure uptrace-go with custom dsn and TLS

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/uptrace#139]
I guess it should be a separate option in Uptrace YAML config

```yaml
uptrace_go:
    dsn: uptrace_dsn
    tls: tls_config_here
```

Which should be used in https://github.com/uptrace/uptrace/blob/master/pkg/bunapp/otel.go#L13-L18
