### ISSUE TITLE
Span data retention

### ISSUE THREAD

**Issue by piotrpersona** [uptrace/uptrace#147]
Hello,

I've seen that some tracing tools provide spans retention, for example: keep span data for 3 days or 2 weeks.
It is possible to enable TTL in on Clickhouse tables.

I would like to request the feature of span data retention.

**Comment by vmihailenco** [comment]
Hello,

This is already possible via the uptrace.yml config:

```yaml
ch_schema:
  spans:
    # Delete spans data after 30 days.
    ttl_delete: 30 DAY
    storage_policy: 'default'

  metrics:
    # Delete metrics data after 90 days.
    ttl_delete: 90 DAY
    storage_policy: 'default'
```

I will update the docs.
