### ISSUE TITLE
Automatically provision metrics dashboards?

### ISSUE THREAD

**Issue by gabriel-v** [uptrace/uptrace#151]
I was looking at [the "Querying Metrics" documentation page](https://uptrace.dev/get/querying-metrics.html) and I am wondering how to automatically provision dashboard from the configuration YML file.

This would be similar to [how Grafana loads dashboard from folders, encoded as JSON](https://grafana.com/tutorials/provision-dashboards-and-data-sources/#provision-a-dashboard).

The documentation page mentions examples like this:
```
metrics:
  - api.user_cache.hits as $hits
  - api.user_cache.misses as $misses
query:
  - per_min($hits) as hits
  - per_min($misses) as misses
  - hits / (hits + misses) as hit_rate
```

...but I don't see in [the configuration file definition](https://github.com/uptrace/uptrace/blob/fc39bb3cb0f0fecca22418839ca57b0e482f816d/example/docker/uptrace.yml) how they are used. I suppose these are actually instructions for clicking in the UI, not code samples?

Questions:
- is there a way to automatically provision metrics dashboards?
- if not, would I achieve this effect by dumping and loading some SQL from the uptrace sqlite database? Which tables?
- would you be interested in a pull request that adds automatic dashboard provisioning? Something like

```
projects:
  - id: 2
    name: dashboards
    token: x
    pinned_attrs:
      - x
    group_by_env: false
    group_funcs_by_service: false
    metrics_dashboards:
      dashboard1:
        type: grid  # | table
        description: example dashboard
        options:
          chart-type: stacked-bar   # | line-chart | area-chart | etc
        metrics:
          - api.user_cache.hits as $hits
          - api.user_cache.misses as $misses
        query:
          - per_min($hits) as hits
          - per_min($misses) as misses
          - hits / (hits + misses) as hit_rate
```

Thank you!
