### ISSUE TITLE
Windows Agent to export logs to uptrace.

### ISSUE THREAD

**Issue by raulpcs** [uptrace/uptrace#161]
Hi, i downloaded the windows binary: [uptrace_windows_amd64.exe](https://github.com/uptrace/uptrace/releases/download/v1.3.1/uptrace_windows_amd64.exe)

but when i run it needs a proper config file.

chatgpt suggested this format.

```
dsn: https://project1_secret_token@http://10.10.1.10:14318/1

logs:
- type: windows
  service: eventlog
  config:
  channels:
    - name: Application
        level: Error
    - name: System
        level: Error
    - name: Security
        level: Error
```

but when i runn it:
uptrace_windows_amd64.exe  --config ./config/uptrace.yml serve

I get this error:

yaml: unmarshal errors:
  line 4: cannot unmarshal !!seq into struct { Level string "yaml:\"level\"" }

I need a little bit of guidance on how can use a windows agent to send critical logs to an uptrace server.
