### ISSUE TITLE
Running multiple uptrace pods connected to the same clickhouse cluster shows different data

### ISSUE THREAD

**Issue by alexandrujieanu** [uptrace/uptrace#183]
Hello,

We have one uptrace cluster (3 pods, with sqlite databases) connected to one clickhouse cluster (3 nodes, plus zookeeper using the bitnami chart). 

The problem we're seeing is that when we click Reload, the page refreshes and the charts and metrics change. For example, sometimes we see radically different data.

This doesn't happen when we scale down uptrace to a single replica.

Do we have to use shared postgresql for the uptrace pods? If so, why is this? Is Uptrace caching some things or is it retrieving all the data from clickhouse?

Thank you!

Alex

**Comment by vmihailenco** [comment]
>Is Uptrace caching some things or is it retrieving all the data from clickhouse?

The actual data in only stored in ClickHouse and we don't use caching.

PostgreSQL is only used for storing metadata like metric names etc. Usually PostgreSQL database is only few megabytes.

>Do we have to use shared postgresql for the uptrace pods? 

Yes, you must use the same PostgreSQL database on all pods.

>The problem we're seeing is that when we click Reload, the page refreshes and the charts and metrics change. For example, sometimes we see radically different data.

If it only happens with metrics, then it can be a bug in the table mode which is already fixed in the cloud version. The bug manifests itself as random values in the table, but sparkline data is unaffected.

Does that sound familiar?

![Uploading table-bug.png…]()

**Comment by darioxtx** [comment]
@alexandrujieanu I had the same issue. If you use bitnami chart and setup few shards and replicas you need to setup uptrace to use cluster setup like:
```
    ch_schema:
      # Compression codec, for example, LZ4, ZSTD(3), or Default.
      compression: ZSTD(3)

      # Whether to use ReplicatedMergeTree instead of MergeTree.
      replicated: true

      # Cluster name for Distributed tables and ON CLUSTER clause.
      cluster: default
```

**Comment by vmihailenco** [comment]
@alexandrujieanu it is true that you need those settings to use ClickHouse cluster, but Uptrace should work without them too. You just won't use ClickHouse cluster features, i.e. all data will be stored on a single node...

**Comment by vmihailenco** [comment]
I need some way to reproduce this issue. We have CickHouse cluster in the [development](https://github.com/uptrace/uptrace/blob/master/docker-compose.yml#L4-L86) environment and it seems to be working as expected when I enable the cluster and reset the schema:

```yaml
ch_schema:
  # Compression codec, for example, LZ4, ZSTD(3), or Default.
  compression: ZSTD(3)

  # Whether to use Replicated* engines.
  replicated: true

  # Cluster name for Distributed tables and ON CLUSTER clause.
  cluster: uptrace1
```

```shell
go run cmd/uptrace/main.go ch reset
```

I am closing this issue for now, but feel free to re-open if it persists with v1.4.x
