### ISSUE TITLE
Correctly parse + escape environment variables in YAML

### ISSUE THREAD

**Issue by paambaati** [uptrace/uptrace#205]
When I try to substitute environment variables for some values in the YAML, it throws errors as they're not correctly serialized.

For example, – 
```yaml
##
## Various options for Uptrace UI.
##
site:
  # Overrides public URL for Vue-powered UI in case you put Uptrace behind a proxy.
  addr: '$UPTRACE_SITE_ADDRESS'
```

throws this error –

```
invalid config /etc/uptrace/uptrace.yml: invalid site.addr option: parse "\"https://uptrace.myapp.com\"": first path segment in URL cannot contain colon
```

Another example is –
```yaml
##
## SMTP settings to send emails.
## https://uptrace.dev/get/alerting.html
##
smtp_mailer:
  enabled: $UPTRACE_SMTP_ENABLED
```

throws this error –

```
line 225: cannot unmarshal !!str `true` into bool
```

I've tried surrounding the variables with both single and double quotes without any luck.
