### ISSUE TITLE
CH: some tables are created under "default" storage_policy but "custom" is defined in uptrace config file

### ISSUE THREAD

**Issue by voriol** [uptrace/uptrace#221]
Hi,

Some tables are created under "default" storage_policy when a "custom" is defined in uptrace config file.

CH:

```
SELECT
    table,
    storage_policy
FROM system.tables
WHERE database = 'uptrace'

Query id: 578be4db-87b1-404e-a335-a76879a4cf4d

┌─table───────────────────────┬─storage_policy───────────────┐
│ ch_migration_locks          │ default                      │
│ ch_migrations               │ default                      │
│ measure_hours               │ custom_policy                │
│ measure_hours_dist          │ default                      │
│ measure_hours_mv            │                              │
│ measure_minutes             │ custom_policy                │
│ measure_minutes_buffer      │                              │
│ measure_minutes_buffer_dist │ default                      │
│ measure_minutes_dist        │ default                      │
│ spans_data                  │ custom_policy                │
│ spans_data_buffer           │                              │
│ spans_data_buffer_dist      │ default                      │
│ spans_index                 │ custom_policy                │
│ spans_index_buffer          │                              │
│ spans_index_buffer_dist     │ default                      │
└─────────────────────────────┴──────────────────────────────┘
```

Uptrace config:

```
ch_schema:
  # Compression codec, for example, LZ4, ZSTD(3), or Default.
  compression: ZSTD(3)

  # Whether to use Replicated* engines.
  replicated: true

  # Cluster name for Distributed tables and ON CLUSTER clause.
  cluster: 1shard_3replicas

  spans:
    # Delete spans data after 30 days.
    ttl_delete: 30 DAY
    storage_policy: 'custom_policy'

  metrics:
    # Delete metrics data after 90 days.
    ttl_delete: 90 DAY
    storage_policy: 'custom_policy'
```

It is possible to define a "custom" storage policy for all tables?

I can't find all the options in the documentation.

Thanks
