### ISSUE TITLE
traces export: context deadline exceeded

### ISSUE THREAD

**Issue by invaderb** [uptrace/uptrace#243]
Gettings,

Uptrace seems really cool and currently trying it out for our company, I got everything setup on an ubuntu 22 server installing with the binary. everything seems to be working however I keep seeing a ton of the following error messages over and over

2023/06/30 20:11:26 traces export: context deadline exceeded: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2023/06/30 20:11:31 failed to upload metrics: context deadline exceeded: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2023/06/30 20:11:36 traces export: context deadline exceeded: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2023/06/30 20:11:46 failed to upload metrics: context deadline exceeded: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2023/06/30 20:11:56 traces export: context deadline exceeded: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp {ip}:14317: i/o timeout"

I set debug to true and set logging to DEBUG but don't see any thing else

**Comment by invaderb** [comment]
It seems like uptrace is no longer reporting once I added the proxy domain and ssl certs but not 100% certain.

Here's my yml file

```yaml
##
## ClickHouse database credentials.
##
ch:
  addr: localhost:9000
  user: default
  password: 
  database: uptrace

  # TLS configuration. Uncomment to enable.
  # tls:
  #   insecure_skip_verify: true # only for self-signed certificates

  # Maximum query execution time.
  max_execution_time: 60s

##
## PostgreSQL db that is used to store metadata such us metric names, dashboards, alerts,
## and so on.
##
pg:
  addr: localhost:5432
  user: uptrace
  password: 
  database: uptrace

  # TLS configuration. Uncomment to enable.
  # tls:
  #   insecure_skip_verify: true # only for self-signed certificates

##
## A list of pre-configured projects. Each project is fully isolated.
##
projects:
  # Conventionally, the first project is used to monitor Uptrace itself.
  - id: 1
    name: Uptrace
    # Token grants write access to the project. Keep a secret.
    token: project1_secret_token
    pinned_attrs:
      - service.name
      - host.name
      - deployment.environment
    # Group spans by deployment.environment attribute.
    group_by_env: false
    # Group funcs spans by service.name attribute.
    group_funcs_by_service: false

  # Other projects can be used to monitor your applications.
  # To monitor micro-services or multiple related services, use a single project.
  - id: 2
    name: My project
    token: project2_secret_token
    pinned_attrs:
      - service.name
      - host.name
      - deployment.environment
    # Group spans by deployment.environment attribute.
    group_by_env: false
    # Group funcs spans by service.name attribute.
    group_funcs_by_service: false

auth:
#  users:
   # - name: John Doe
   #   email: 
   #   password:
   #   notify_by_email: true

  # OpenID Connect (Single Sign-On)
  oidc:
    # The ID is used in API endpoints, for example, in redirect URL
    # `http://<uptrace-host>/api/v1/sso/<oidc-id>/callback`.
     - id: azure_ad
    #   # Display name for the button in the login form.
    #   # Default to 'OpenID Connect'
       display_name: azure_ad
    #   # The base URL for the OIDC provider.
       issuer_url: 
    #   # The OAuth 2.0 Client ID
       client_id: 
    #   # The OAuth 2.0 Client Secret
       client_secret: 
    #   # Additional OAuth 2.0 scopes to request from the OIDC provider.
    #   # Defaults to 'profile'. 'openid' is requested by default and need not be specified.
       scopes:
         - profile

##
## Create metrics from spans and events.
##
metrics_from_spans:
  - name: uptrace.tracing.spans
    description: Spans duration (excluding events)
    instrument: histogram
    unit: microseconds
    value: .duration / 1000
    attrs:
      - .system
      - .group_id
      - service.name
      - host.name
      - .status_code
    annotations:
      - display.name
    where: .event_name = ''

  - name: uptrace.tracing.events
    description: Events count (excluding spans)
    instrument: counter
    unit: 1
    value: .count
    attrs:
      - .system
      - .group_id
      - .name
      - host.name
    annotations:
      - display.name
    where: .is_event = 1

##
## Various options to tweak ClickHouse schema.
## For changes to take effect, you need reset the ClickHouse database with `ch reset`.
##
ch_schema:
  # Compression codec, for example, LZ4, ZSTD(3), or Default.
  compression: ZSTD(3)

  # Whether to use Replicated* engines.
  replicated: false

  # Cluster name for Distributed tables and ON CLUSTER clause.
  #cluster: uptrace1

  spans:
    # Delete spans data after 30 days.
    ttl_delete: 30 DAY
    storage_policy: 'default'

  metrics:
    # Delete metrics data after 90 days.
    ttl_delete: 90 DAY
    storage_policy: 'default'

##
## Addresses on which Uptrace receives gRPC and HTTP requests.
##
listen:
  # OTLP/gRPC API.
  grpc:
    addr: ':14317'
    tls:
        cert_file: /etc/letsencrypt/live/{domain}/fullchain.pem
        key_file: /etc/letsencrypt/live/{domain}/privkey.pem
    # tls:
    #   cert_file: config/tls/uptrace.crt
    #   key_file: config/tls/uptrace.key

  # OTLP/HTTP API and Uptrace API with Vue UI.
  http:
    addr: ':14318'
    tls:
        cert_file: /etc/letsencrypt/live/{domain}/fullchain.pem
        key_file: /etc/letsencrypt/live/{domain}/privkey.pem

##
## Various options for Uptrace UI.
##
site:
  # Overrides public URL for Vue-powered UI.
  addr: 'https://{domain}:443'

##
## Spans processing options.
##
spans:
  # The size of the Go chan used to buffer incoming spans.
  # If the buffer is full, Uptrace starts to drop spans.
  #buffer_size: 100000

  # The number of spans to insert in a single query.
  #batch_size: 10000

##
## Metrics processing options.
##
metrics:
  # List of attributes to drop for being noisy.
  drop_attrs:
    - telemetry.sdk.language
    - telemetry.sdk.name
    - telemetry.sdk.version

  # The size of the Go chan used to buffer incoming measures.
  # If the buffer is full, Uptrace starts to drop measures.
  #buffer_size: 100000

  # The number of measures to insert in a single query.
  #batch_size: 10000

  # The size of the buffer for converting cumulative metrics to delta.
  #cum_to_delta_size: 100000

##
## SMTP settings to send emails.
## https://uptrace.dev/get/alerting.html
##
smtp_mailer:
  enabled: false
  host: localhost
  port: 1025
  username: mailhog
  password: mailhog
  from: 'uptrace@localhost'

##
## uptrace-go client configuration.
## Uptrace sends internal telemetry here. Defaults to listen.grpc.addr.
##
uptrace_go:
   dsn: https://project1_secret_token@{domain}:14317/1
   tls:
       cert_file: /etc/letsencrypt/live/{domain}/fullchain.pem
       key_file: /etc/letsencrypt/live/{domain}/privkey.pem
  #   cert_file: config/tls/uptrace.crt
  #   key_file: config/tls/uptrace.key
  #   insecure_skip_verify: true

##
## Logging configuration.
##
logging:
  # Zap minimal logging level.
  # Valid values: DEBUG, INFO, WARN, ERROR, DPANIC, PANIC, FATAL.
  level: INFO

# Secret key that is used to sign JWT tokens etc.
secret_key: 

# Enable to log HTTP requests and database queries.
debug: false
```
