### ISSUE TITLE
Feature: Save Filters / Configurable Default Landing Page

### ISSUE THREAD

**Issue by jkrech17** [uptrace/uptrace#25]
It could be beneficial to allow the main summary view in Uptrace to be configurable by a particular attribute.  Right now there are Systems, Services, and hosts but say you had an attribute of app.name.  It would be useful to be able to add additional views based on some attributes users have added to a group by Application, etc.  

![image](https://user-images.githubusercontent.com/3282447/160913371-f4fe3ef2-24e7-44f8-9e8a-4e07e2252c5e.png)

We may look at how this could be implemented and could look to contribute, but thought I would submit an issue as well.

Thanks!

**Comment by vmihailenco** [comment]
Before we discuss how to implement this, did you consider using `group by app.name` in Explore tab? That is more or less the same data, but with the ability to add/remove columns & apply filters.

![explore-group-by](https://user-images.githubusercontent.com/290976/161001654-838b917f-af45-4213-823e-fb25de0d411c.png)

The only missing feature is that Uptrace does not allow to remember filters. So perhaps we should address that instead of adding custom tabs in Overview?

**Comment by jkrech17** [comment]
I was thinking something similar but did not write it that way. I think saved filters would be a great feature, but I still think it would be useful for the main landing page to default to a saved filter the user selected.  When there are a large number of services exist system:service name page is fairly long and almost always default to some type of exploration.  Allowing a saved filter as default help user set their interested context more quickly.

**Comment by vmihailenco** [comment]
You can now pin attributes on the overview page via YAML config:

```yaml
  - id: 1
    name: Uptrace
    # Token grants write access to the project. Keep a secret.
    token: project1_secret_token
    pinned_attrs:
      - service.name
      - host.name
      - deployment.environment
```

Query history is planned for later.
