### ISSUE TITLE
Clickhouse config - CA

### ISSUE THREAD

**Issue by RouR** [uptrace/uptrace#266]
Please add an option to specify the path to the root certificate.

https://github.com/uptrace/uptrace/blob/87cebed4f65bff815e63a9b09368fb5ac9e30cf7/pkg/bunconf/tls.go#L111C12-L111C12

**Comment by vmihailenco** [comment]
I believe it is called `ca_file` - https://github.com/uptrace/uptrace/blob/87cebed4f65bff815e63a9b09368fb5ac9e30cf7/pkg/bunconf/tls.go#L17-L19

**Comment by RouR** [comment]
Sorry, I can't understand - Is this setting for the uptrace server, for the client to Clickhouse or database?

**Comment by vmihailenco** [comment]
It is a general way to configure TLS whenever a TLS config is accepted, e.g.

```yaml
pg:
  tls:
    ca_file: ...

ch:
  tls:
    ca_file: ...

listen:
  http:
    tls:
      ca_file: ...
```
