### ISSUE TITLE
Total server memory cannot be obtained through prometheus

### ISSUE THREAD

**Issue by QuanZi123** [uptrace/uptrace#306]
uptrace version :  v1.6.0-rc.2
prometheus version : 2.48.0
prometheus node_exporter version：1.6.1

uptrace.yml Add the following configuration
```
  - id: 2
    name: My project 1
    token: project2_secret_token
    pinned_attrs:
      - service.name
      - host.name
      - deployment.environment
    # Group spans by deployment.environment attribute.
    group_by_env: false
    # Group funcs spans by service.name attribute.
    group_funcs_by_service: false
```
prometheus.yml Add the following configuration
```
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node1"
    static_configs:
      - targets: ["localhost:9100"]

remote_write:
  - url: 'http://localhost:14318/api/v1/prometheus/write'
    headers: { 'uptrace-dsn': 'http://project2_secret_token@localhost:14318?grpc=14317' }
```

**After the construction was completed, the metrics module queried the free memory of node1 node successfully**

![freeMem](https://github.com/uptrace/uptrace/assets/142292346/4c25f442-795b-41e8-8c02-38e431168cc1)

**The query for total memory in prometheus was successful, but the query value in uptrace is 0**

<img width="950" alt="promTotalMem" src="https://github.com/uptrace/uptrace/assets/142292346/99cd89ef-05b4-43bc-a220-1b0cde0245b3">

![totalMem](https://github.com/uptrace/uptrace/assets/142292346/552cb883-d1e6-4778-9500-da2972e26254)
