### ISSUE TITLE
Provide a way to disable mail SMTP STARTTLS and TLS

### ISSUE THREAD

**Issue by rgl** [uptrace/uptrace#344]
I'm trying to modify the [uptrace docker example](https://github.com/uptrace/uptrace/blob/master/example/docker/docker-compose.yml) to replace [MailHog](https://github.com/mailhog/MailHog) with [Mailpit](https://github.com/axllent/mailpit), but I didn't find a way to completely disable STARTTLS or TLS.

This is required even with MailHog, as uptrace cannot connect to the SMTP server endpoint due to:

```console
$ docker compose logs uptrace --follow
uptrace-1  | 2024-02-24T17:34:13.162Z   error   backend/log.go:25       job failed (will retry) {"task_name": "notify-by-email", "reserved_count": 3, "delay": 120, "error": "dial failed: SMTP AUTH failed: unencrypted connection"}
```

FWIW, I've been playing with the used go library at https://github.com/rgl/use-go-mail, and I've used a URL syntax to configure the mail server address. It supports two URL schemes:

1. `smtps://mailpit:1025`: uses a tls connection.
2. `smtp://mailpit:1025`: uses a plaintext tcp connection.

The relevant code is at https://github.com/rgl/use-go-mail/blob/b7e79e055fa35b9ea74fd40bdd971846f9049804/main.go#L114-L130

I can submit a PR. What do you think about adding the following `protocol` field?

```yml

smtp_mailer:
  enabled: true
  protocol: smtp
  host: mailpit
  port: 1025
  username: uptrace
  password: uptrace
  from: 'uptrace@localhost'
```

`protocol` could be one of:

* `smtp` (or `tcp`?): tcp plaintext connection.
* `smtps` (or `tls`?): force the use of TLS from the start; never allow plaintext connection.
* `starttls`: uses STARTTLS over plaintext or fails. (the current behaviour).

**Comment by marco-arnold** [comment]
I encountered the same issue with Mailhog. After perusing the source code, I discovered the undocumented "auth_type" option (see https://github.com/wneessen/go-mail/blob/1c883a8ed4182f07165a2a6b33b4151b7cd70e98/auth.go#L23). Setting an empty value equates to the SMTPAuthNoAuth value. 

Here is my working sample config:
```yml
smtp_mailer:
  enabled: true
  host: mailhog
  port: 1025
  auth_type: ''
```
