### ISSUE TITLE
Improve documentation for environment variables in config

### ISSUE THREAD

**Issue by demurgos** [uptrace/uptrace#355]
Hello, I am working on a deployment script for Uptrace and I am trying to understand how environment variables interact with the config file.
The [current documentation](https://uptrace.dev/get/config.html#environment-variables) is relatively terse:

> You can use environment variables in the YAML config file, for example:
>
> ```yaml
> pg:
>   addr: ${UPTRACE_PG_ADDR}
>   user: ${UPTRACE_PG_USER}
>   password: ${UPTRACE_PG_PASSWORD}
>   database: ${UPTRACE_PG_DATABASE:uptrace}
> ```
>
> Environment variables can have a default value, for example, `${ENV_VAR_NAME:default_value}`.

Could you please update the documentation to clarify the following questions please?

1. Are environment variables expanded before or after parsing the YAML content? In other words, assuming `UPTRACE_PG_USER="user: uptrace"`, is the following block valid?
   ```yaml
   pg:
     addr: "localhost:5432"
     ${UPTRACE_PG_USER}
     password: "dev"
    // ...
   ```
2. Are environment variables resolved recursively or not? In other words, assuming `ADMIN_USER="uptrace_pg_admin"` and `UPTRACE_PG_USER="ADMIN_USER"`, is the following block valid?
   ```yaml
   pg:
     addr: "localhost:5432"
     user: ${${UPTRACE_PG_USER}}
     password: "dev"
    // ...
   ```

3. Are environment variable default values resolved recursively or not? In other words, assuming `ADMIN_USER="uptrace_pg_admin"`, is the following block valid?
   ```yaml
   pg:
     addr: "localhost:5432"
     user: ${UPTRACE_PG_USER:${ADMIN_USER}}
     password: "dev"
    // ...
   ```
