### ISSUE TITLE
Errors in uptrace container logs: job failed (will retry)

### ISSUE THREAD

**Issue by bmday** [uptrace/uptrace#362]
We are using uptrace 1.6.1 in docker-compose.

```
version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.7
    hostname: clickhouse
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - /storage/uptrace/ch_data9:/var/lib/clickhouse
    ports:
      - '18123:8123'
      - '19000:9000'
    logging:
      options:
        max-size: '50m'
        max-file: '1'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  postgres:
    image: postgres:15-alpine
    hostname: postgresql
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: <user>
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: uptrace
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U uptrace -d uptrace']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - './uptrace_data/pg_data6:/var/lib/postgresql/data/pgdata'
    ports:
      - '15432:5432'
    logging:
      options:
        max-size: '50m'
        max-file: '1'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 1G

  uptrace:
    image: 'uptrace/uptrace:1.6.1'
    hostname: uptrace
    restart: on-failure
    depends_on:
      - clickhouse
      - postgres
    volumes:
      - ./uptrace_data/uptrace.yml:/etc/uptrace/uptrace.yml
#    entrypoint: /uptrace ch reset
    #environment:
    #  - DEBUG=2
    ports:
      - '14317:14317'
      - '14318:14318'
    logging:
      options:
        max-size: '50m'
        max-file: '1'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.89.0
    hostname: otelcol
    restart: on-failure
    depends_on:
     - uptrace
    volumes:
      - ./uptrace_data/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - '4317:4317'
      - '4318:4318'
      - '14250:14250'
    logging:
      options:
        max-size: '50m'
        max-file: '1'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

  vector:
    image: timberio/vector:0.28.X-alpine
    hostname: vector
    depends_on:
     - uptrace
    volumes:
      - ./uptrace_data/vector.toml:/etc/vector/vector.toml:ro
    logging:
      options:
        max-size: '50m'
        max-file: '1'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 1G

```

In the uptrace container log we often see the error:
```
2024-04-16T10:24:29.868Z        error   backend/log.go:25       job failed (will retry) {"task_name": "create-error-alert", "reserved_count": 9, "delay": 1800, "error": "name can't be empty"}
github.com/vmihailenco/taskq/v4/backend.Error
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/backend/log.go:25
github.com/vmihailenco/taskq/v4.(*Consumer).release
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/consumer.go:426
github.com/vmihailenco/taskq/v4.(*Consumer).Put
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/consumer.go:421
github.com/vmihailenco/taskq/v4.(*Consumer).Process
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/consumer.go:398
github.com/vmihailenco/taskq/v4.(*Consumer).worker
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/consumer.go:353
github.com/vmihailenco/taskq/v4.(*Consumer).Start.func1
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/consumer.go:153
2024-04-16T10:27:56.643Z        error   backend/log.go:25       job failed (will retry) {"task_name": "create-error-alert", "reserved_count": 13, "delay": 1800, "error": "name can't be empty"}
github.com/vmihailenco/taskq/v4/backend.Error
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/backend/log.go:25
github.com/vmihailenco/taskq/v4.(*Consumer).release
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/consumer.go:426
github.com/vmihailenco/taskq/v4.(*Consumer).Put
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/consumer.go:421
github.com/vmihailenco/taskq/v4.(*Consumer).Process
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/consumer.go:398
github.com/vmihailenco/taskq/v4.(*Consumer).worker
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/consumer.go:353
github.com/vmihailenco/taskq/v4.(*Consumer).Start.func1
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/consumer.go:153
2024-04-16T10:28:33.265Z        error   backend/log.go:25       job failed (will retry) {"task_name": "create-error-alert", "reserved_count": 10, "delay": 1800, "error": "name can't be empty"}
github.com/vmihailenco/taskq/v4/backend.Error
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/backend/log.go:25
github.com/vmihailenco/taskq/v4.(*Consumer).release
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/consumer.go:426
github.com/vmihailenco/taskq/v4.(*Consumer).Put
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/consumer.go:421
github.com/vmihailenco/taskq/v4.(*Consumer).Process
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/consumer.go:398
github.com/vmihailenco/taskq/v4.(*Consumer).worker
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/consumer.go:353
github.com/vmihailenco/taskq/v4.(*Consumer).Start.func1
        github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/consumer.go:153
```

Why might this error occur? We have not set up any alerts.
