### ISSUE TITLE
Is it possible to add simple user-project relation?

### ISSUE THREAD

**Issue by azat** [uptrace/uptrace#370]
AFAICS there is such support in cloud - organizations, but not in an open-source version.
Simple mapping via YAML will work, i.e.:

```yaml
auth:
  users:
    - name: Anonymous
      email: uptrace@localhost
      password: uptrace
      notify_by_email: true
      projects: [ids_or_names]
```

Or maybe you will accept a patch for this?
