### ISSUE TITLE
Uptrace config: allow to import secret values from Docker Swarm Secrets

### ISSUE THREAD

**Issue by amedveshchek** [uptrace/uptrace#382]
Currently Uptrace config (`uptrace.yaml`) allows to conveniently import secrets and config values from environment variables
```
param: ${ENVIRONMENT_VARIABLE:default_fallback_value}
```
Docker Swarm has a way to store [secrets](https://docs.docker.com/engine/swarm/secrets/) and [configs](https://docs.docker.com/engine/swarm/configs/) and share them among the cluster nodes. In docker container it'll be located at:
  - secrets: `/run/secrets/<secret_name>`
  - configs: `/<config_name>`

Proposal is to introduce extended syntax, for importing Docker Swarm Secrets and Configs.

E.g.:
```
secret_param: ${secret=<secret_name>}   # reads value of /run/secrets/<secret_name>
config_param: ${config=<config_name>}   # reads value of /<config_name>
```
And it will look like this:
```
pg:
  addr: postgres:5432
  user: ${config=uptrace-postgres-user}
  password: ${secret=uptrace-postgres-password}
  database: uptrace
```
