### ISSUE TITLE
Unable to configure SSO using Microsoft Entra

### ISSUE THREAD

**Issue by wertzui** [uptrace/uptrace#392]
I want to use SSO with our organizational microsoft accounts.
However I always get the following JSON error displayed in the browser after entering my login credentials on the microsoft website

```json
{
    "error": {
        "status": 500,
        "code": "internal",
        "message": "*fmt.wrapError: oidc: failed to get user info: 401 Unauthorized: {\"error\":{\"code\":\"InvalidAuthenticationToken\",\"message\":\"Access token validation failure. Invalid audience.\",\"innerError\":{\"date\":\"2024-06-24T14:05:40\",\"request-id\":\"f50b0836-1b4d-4d1d-86de-8b5177089b2a\",\"client-request-id\":\"f50b0836-1b4d-4d1d-86de-8b5177089b2a\"}}}"
    },
    "statusCode": 500,
    "traceId": "17dbf5cc3dfa686e89ed9a8dc19cc117"
}
```

I've configured the following:
```yaml
    auth:
      oidc:
      - claim: oid
        client_id: ccc
        client_secret: sss
        display_name: Microsoft Account
        id: Uptrace
        issuer_url: https://login.microsoftonline.com/ttt/v2.0
        scopes:
        - api://ccc/access
```

The following values are from the app registration that I've created in the Azure portal:

| Value | Meaning |
| - | - |
| ccc | client-id (a GUID) |
| sss | client-secret (a secret string, no special format) |
| ttt | tenant-id (a GUID) |

The scope is the one, which I've created in the Azure portal.
