### ISSUE TITLE
Distributed tables are not created in Clickhouse cluster

### ISSUE THREAD

**Issue by STI26** [uptrace/uptrace#398]
Hello
When using clickhouse cluster with several shards, data is stored only on one.
I think this is because distributed tables are not created.

| Table | Total rows (shard 1 / replica 1) | Total rows (shard 1 / replica 2) | Total rows (shard 2 / replica 1) | Total rows (shard 2 / replica 2) |
| ----- | -------------------------------- | -------------------------------- | -------------------------------- | -------------------------------- |
| spans_index_buffer | 0 | 0 | 0 | 0 |
| spans_index | 83130 | 83422 | 0 | 0 |
| spans_data_buffer | 0 | 0 | 0 | 0 |
| spans_data | 83130 | 83422 | 0 | 0 |
| service_graph_edges_buffer | 0 | 0 | 0 | 0 |
| service_graph_edges | 668 | 668 | 0 | 0 |
| metrics_uptrace_tracing_spans_mv | 0 | 0 | 0 | 0 |
| metrics_uptrace_tracing_events_mv | 0 | 0 | 0 | 0 |
| metrics_uptrace_service_graph_server_duration_mv | 0 | 0 | 0 | 0 |
| metrics_uptrace_service_graph_failed_requests_mv | 0 | 0 | 0 | 0 |
| metrics_uptrace_service_graph_client_duration_mv | 0 | 0 | 0 | 0 |
| datapoint_minutes_buffer | 0 | 0 | 0 | 0 |
| datapoint_minutes | 1329891 | 1334980 | 0 | 0 |
| datapoint_hours_mv | 0 | 0 | 0 | 0 |
| datapoint_hours | 8276 | 8282 | 0 | 0 |
| ch_migrations_dist | 0 | 0 | 0 | 0 |
| ch_migrations | 0 | 0 | 2 | 2 |
| ch_migration_locks | 0 | 0 | 0 | 0 |

I've configured the following:
```
ch_schema:
  # Compression codec, for example, LZ4, ZSTD(3), or Default.
  compression: ZSTD(3)

  # Whether to use ReplicatedMergeTree instead of MergeTree.
  replicated: true

  # Cluster name for Distributed tables and ON CLUSTER clause.
  cluster: uptrace-cluster1

  spans:
    # Delete spans data after 30 days.
    ttl_delete: 7 DAY
    storage_policy: 'default'

  metrics:
    # Delete metrics data after 90 days.
    ttl_delete: 30 DAY
    storage_policy: 'default'
```
Configuration of the clickhouse cluster from the [example](https://github.com/uptrace/uptrace/blob/master/docker-compose.yml) was used.
