### ISSUE TITLE
Alert not triggering?

### ISSUE THREAD

**Issue by Danferno** [uptrace/uptrace#435]
Am I doing something wrong? I have set up a trace event with event_name failure and want to get Slack notifications whenever such an event occurs. I see these events in the uptrace overview and set up following monitor:
```
monitors:
  - name: failure
    type: metric
    notify_everyone_by_email: true
    metrics:
      - uptrace_tracing_events as $events
    query:
      - perMin(sum($events))
      - where _event_name = "failure"
    column: perMin(sum($events))
    grouping_interval: 1m0s
    check_num_point: 1
    null_points: convert
    max_allowed_value: 0
    flapping: null
```
And as you can see in the attached screenshot, it is correctly identifying these events. I played around with grouping interval and check_num_point but that doesn't seem to do anything. What am I missing and/or is there a better way to do this?

![sequenza alert](https://github.com/user-attachments/assets/5e19584b-3d4a-4a17-ad50-324e9dbe9370)
