### ISSUE TITLE
`Unsupported attribute type	{"type": "map[string]interface {}"}` error at getting trace details after Graphana version update

### ISSUE THREAD

**Issue by Dima-Diachenko** [uptrace/uptrace#489]
Hello,

We're using Uptrace deployment with Helm chart, latest version 1.7.7. 
All is great, thanks for the product!

And we have Grafana, that uses Uptrace as a Tempo kind datasource to get traces:

```yaml
  tempo-ds.yaml: |-
    apiVersion: 1
    datasources:
      - uid: tempo-uid
        name: 'Traces'
        orgId: 1
        type: tempo
        url: 'http://uptrace.uptrace:14318/api/tempo/2'
        access: proxy
        basicAuth: false
        isDefault: false
        jsonData:
          httpHeaderName1: Authorization
          timeout: 180
          httpMethod: GET
          serviceMap:
            datasourceUid: 'metrics'
          nodeGraph:
            enabled: true
          tracesToLogs:
            datasourceUid: Logs
            filterBySpanID: true
            filterByTraceID: true
            mapTagNamesEnabled: true
            mappedTags:
              - key: deployment.environment
                value: env
            spanEndTimeShift: "1h"
            spanStartTimeShift: "-1h"
          tracesToMetrics:
            datasourceUid: metrics
            queries:
              - name: Request rate
                query: sum by (client, server)(rate(traces_service_graph_request_total{$$__tags}[$$__rate_interval]))
              - name: Error rate
                query: sum by (client, server)(rate(traces_service_graph_request_failed_total{$$__tags}[$$__rate_interval]))
              - name: p90 latency
                query: histogram_quantile(0.9, sum(rate(traces_service_graph_request_server_seconds_bucket{$$__tags}[$$__rate_interval])) by (le, client, server))
            tags:
              - key: service.name
                value: server
        secureJsonData:
          httpHeaderValue1: 'Bearer <masked>'
        editable: true
        readOnly: false
```

Everything worked well, **until update Grafana from v11.1.5 v11.5.2**

Connection to the Uptrace datasource still exists and working, I'm able to get traces!

But if I try to see trace details - instead of spans I'm getting error:

`Internal Server Error - please inspect Grafana server log for details`

<img width="1451" alt="Image" src="https://github.com/user-attachments/assets/d2bb9f54-d591-40c1-a56b-a8f449311f25" />

After some investigation I've found the root cause, from the Uptrace side we have following error:
```
2025-03-03T10:17:11.513Z	error	grafana/tempopb.go:278	unsupported attribute type	{"type": "map[string]interface {}"}
github.com/uptrace/uptrace/pkg/grafana.tempoAnyValue
	github.com/uptrace/uptrace/pkg/grafana/tempopb.go:278
github.com/uptrace/uptrace/pkg/grafana.tempoResourceAndAttributes
	github.com/uptrace/uptrace/pkg/grafana/tempopb.go:151
github.com/uptrace/uptrace/pkg/grafana.tempoResourceSpans
	github.com/uptrace/uptrace/pkg/grafana/tempopb.go:43
github.com/uptrace/uptrace/pkg/grafana.newTempopbTrace
	github.com/uptrace/uptrace/pkg/grafana/tempopb.go:33
github.com/uptrace/uptrace/pkg/grafana.(*TempoHandler).queryTrace
	github.com/uptrace/uptrace/pkg/grafana/tempo_handler.go:76
github.com/uptrace/uptrace/pkg/grafana.(*TempoHandler).QueryTrace
	github.com/uptrace/uptrace/pkg/grafana/tempo_handler.go:50
github.com/uptrace/uptrace/pkg/org.(*Middleware).UserAndProject-fm.(*Middleware).UserAndProject.func1
	github.com/uptrace/uptrace/pkg/org/auth.go:105
github.com/uptrace/bunrouter/extra/bunrouterotel.(*config).Middleware-fm.(*config).Middleware.func1
	github.com/uptrace/bunrouter/extra/bunrouterotel@v1.0.21/bunrouterotel.go:70
github.com/uptrace/uptrace/pkg/bunapp.(*App).httpErrorHandler-fm.(*App).httpErrorHandler.func1
	github.com/uptrace/uptrace/pkg/bunapp/app.go:231
github.com/uptrace/bunrouter/extra/reqlog.(*middleware).Middleware-fm.(*middleware).Middleware.func1
	github.com/uptrace/bunrouter/extra/reqlog@v1.0.21/middleware.go:77
github.com/uptrace/bunrouter.(*Router).ServeHTTPError
	github.com/uptrace/bunrouter@v1.0.21/router.go:52
github.com/uptrace/bunrouter.(*Router).ServeHTTP
	github.com/uptrace/bunrouter@v1.0.21/router.go:45
github.com/klauspost/compress/gzhttp.NewWrapper.func1.1
	github.com/klauspost/compress@v1.17.6/gzhttp/compress.go:495
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2171
github.com/uptrace/uptrace/pkg/httputil.DecompressHandler.ServeHTTP
	github.com/uptrace/uptrace/pkg/httputil/middleware.go:53
github.com/uptrace/uptrace/pkg/httputil.(*TraceparentHandler).ServeHTTP
	github.com/uptrace/uptrace/pkg/httputil/middleware.go:90
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.48.0/handler.go:225
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.48.0/handler.go:83
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2171
main.init.func2.(*Cors).Handler.11
	github.com/rs/cors@v1.10.1/cors.go:281
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2171
github.com/uptrace/uptrace/pkg/httputil.PanicHandler.ServeHTTP
	github.com/uptrace/uptrace/pkg/httputil/middleware.go:31
net/http.serverHandler.ServeHTTP
	net/http/server.go:3142
net/http.(*conn).serve
	net/http/server.go:2044
2025-03-03T10:17:11.513Z	error	grafana/tempopb.go:278
```

I've tried to fix it by changing different options from the Grafana dashboard side and from Uptrace config, but looks like it's some compatibility issue. Because it works as expected with previous Graphana versions (rollback fixed the issue). But with latest update this integration partially degraded.

Can I ask you to take a look? I'm ready to share any additional details that you may need to, just ask me. 
Hope for your support here.
