### ISSUE TITLE
`error reading server preface: http2: frame too large` errors at Graphana connections

### ISSUE THREAD

**Issue by Dima-Diachenko** [uptrace/uptrace#490]
Hello guys, 

We're using latest Uptrace v1.7.7, deployed via Helm, everything looks good!

But I've started to notice errors in Grafana logs, e.g.:

```
level=info msg="[core] [Channel #2 SubChannel #3]grpc: addrConn.createTransport failed to connect to {Addr: \"uptrace1.uptrace:14318\", ServerName: \"uptrace1.uptrace:14318\", }. Err: connection error: desc = \"error reading server preface: http2: frame too large\""
```

Here is the configuration of our Grafana Tempo datasouce, we're using Tempo api endpoing that you are providing:

```yaml
  tempo-ds.yaml: |-
    apiVersion: 1
    datasources:
      - uid: tempo-uid
        name: 'Traces'
        orgId: 1
        type: tempo
        url: 'http://uptrace.uptrace:14318/api/tempo/2'
        access: proxy
        basicAuth: false
        isDefault: false
        jsonData:
          httpHeaderName1: Authorization
          timeout: 180
          httpMethod: GET
          serviceMap:
            datasourceUid: 'metrics'
          nodeGraph:
            enabled: true
          tracesToLogs:
            datasourceUid: Logs
            filterBySpanID: true
            filterByTraceID: true
            mapTagNamesEnabled: true
            mappedTags:
              - key: deployment.environment
                value: env
            spanEndTimeShift: "1h"
            spanStartTimeShift: "-1h"
          tracesToMetrics:
            datasourceUid: metrics
            queries:
              - name: Request rate
                query: sum by (client, server)(rate(traces_service_graph_request_total{$$__tags}[$$__rate_interval]))
              - name: Error rate
                query: sum by (client, server)(rate(traces_service_graph_request_failed_total{$$__tags}[$$__rate_interval]))
              - name: p90 latency
                query: histogram_quantile(0.9, sum(rate(traces_service_graph_request_server_seconds_bucket{$$__tags}[$$__rate_interval])) by (le, client, server))
            tags:
              - key: service.name
                value: server
        secureJsonData:
          httpHeaderValue1: 'Bearer <masked>'
        editable: true
        readOnly: false
```

Uptrace configuration (values file):

```yaml
clickhouse:
  enabled: false
postgresql:
  enabled: false
ingress:
  enabled: false
otelcol:
  enabled: false
utprace:
  service:
    type: LoadBalancer
    http_port: 14318
    grpc_port: 14317
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
      external-dns.alpha.kubernetes.io/hostname: uptrace1.azure.internal
uptrace:
  replicaCount: 2
  image:
    repository: <replaced>.azurecr.io/uptrace/uptrace
    tag: 1.7.7
  config:
    site:
      addr: 'https://uptrace.<replaced>.io'
    auth:
      oidc:
        - id: azure
          display_name: Azure Login
          issuer_url: <masked>
          client_id: <masked>
          client_secret: <masked>
          scopes:
            - profile
            - openid
            - email
          claim: email
      users:
        - email: admin@localhost
          name: Anonymous
          notify_by_email: true
          password: <masked>
          auth_token: <masked>
    ch:
      addr: <replaced>.azure.internal:9000
      user: uptrace
      password: uptrace
      database: uptrace
    ch_schema:
      compression: ZSTD(3)
      metrics:
        storage_policy: default
        ttl_delete: 11 DAY
      replicated: false
      spans:
        storage_policy: default
        ttl_delete: 11 DAY

    metrics_from_spans:
      - name: <replaced>.tracing.spans
        description: Spans duration (excluding events)
        instrument: histogram
        unit: microseconds
        value: _duration / 1000
        attrs:
          - _system
          - _kind
          - _name
          - _group_id
          # - application
          - service_name
          - service_version
          # - cluster
          # - env
          - deployment_environment
          # - k8s_pod_name
          # - http_host
          - http_route
          - http_request_method
          - http_response_status_code
          - _status_code
          # - net_peer_name as net_peer_name
        annotations:
          - display_name
        where: _event_name = ''

    projects:
      - id: 1
        name: Uptrace
        token: project1_secret_token
        pinned_attrs:
          - service_name
          - host_name
          - deployment_environment
        group_by_env: false
        group_funcs_by_service: false
        prom_compat: true
      - id: 2
        name: <replaced>
        token: project2_secret_token
        pinned_attrs:
          - deployment_environment
          # - application
          - service_name
        group_by_env: false
        group_funcs_by_service: true
        prom_compat: true
    uptrace_go:
      disabled: false
      dsn: http://project1_secret_token@uptrace1:14317/1

    logging:
      level: ERROR
  service:
    type: LoadBalancer
    http_port: 14318
    grpc_port: 14317
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
      external-dns.alpha.kubernetes.io/hostname: uptrace1.azure.internal

nodeSelector:
  dedicated: observability

tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 30
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 30
  - key: "dedicated"
    value: "observability"
    operator: "Equal"
    effect: "NoSchedule"
  - key: "kubernetes.azure.com/scalesetpriority"
    value: "spot"
    operator: "Equal"
    effect: "NoSchedule"
```

Unfortunately, grpc address like `grpc://uptrace1.uptrace:14317` wouldn't work (I tried), so we have to use http endpoint and see these errors. And can't find how to change configs for https2.

Maybe you already have faced with it and have some recommendations to fix it?

By the way, in Grafana latest versions we may see following warning. Maybe it's related:

<img width="1045" alt="Image" src="https://github.com/user-attachments/assets/13f7d60f-db8f-4e7f-b170-2e35b1d909ad" />

Thanks in advance for looking that!
