### ISSUE TITLE
About mailer config error

### ISSUE THREAD

**Issue by juaby** [uptrace/uptrace#506]
**branch**: v2.0.0-beta4
**image**: 'uptrace/uptrace:2.0.0-beta4'

```

when: use smtp_mailer config
     error: unknown field "smtp_mailer"
then: use mailer: and tls: { disabled: true }
     error: unknown field "disabled"

```

**config#1**: config/uptrace.dist.yml
```
mailer:
  smtp:
    enabled: false
    host: localhost
    port: 1025
    username: mailhog
    password: mailhog
    tls: { disabled: true }
    from: uptrace@localhost
```

**config#2**: config/uptrace.yml
```
smtp_mailer:
  enabled: true
  host: localhost
  port: 1025
  username: mailpit
  password: mailpit
  tls: { disabled: true }
  from: uptrace@localhost
```

**config#3**: example/docker/uptrace.yml
```
mailer:
  smtp:
    enabled: false
    host: localhost
    port: 1025
    username: mailhog
    password: mailhog
    tls: { disabled: true }
    from: uptrace@localhost
```

but
**code#4**: pkg/bunconf/config.go
```
SMTPMailer struct {
	Enabled bool   yaml:"enabled"
	From    string yaml:"from"

	Host     string            yaml:"host"
	Port     int               yaml:"port"
	AuthType mail.SMTPAuthType yaml:"auth_type"
	Username string            yaml:"username"
	Password string            yaml:"password"
	TLS      *TLSClient        yaml:"tls"
} yaml:"smtp_mailer"
```

**Comment by vmihailenco** [comment]
Please use the example from [documentation](https://uptrace.dev/get/hosted/config#sending-emails):


```yaml
##
## To receive email notifications, configure a mailer.
## https://uptrace.dev/features/alerting
##
mailer:
  smtp:
    # Whether to use this mailer for sending emails.
    enabled: true
    # SMTP server host.
    host: localhost
    # SMTP server port.
    port: 1025
    # Username for authentication.
    username: mailhog
    # Password for authentication.
    password: mailhog
    # Uncomment to disable opportunistic TLS.
    #tls: { insecure: true }
    # Emails will be send from this address.
    from: 'uptrace@localhost'
```
