### ISSUE TITLE
Need some persistent config for projects

### ISSUE THREAD

**Issue by dontepanlin** [uptrace/uptrace#507]
I don't know why you choose database based configuration only in version 2.0.0. It's like backward evolution. For example, Grafana evolutionized forward with dashboards provisioners.

How to deal with predefined env kubernetes? Old desing was little rough, but it works fine

**Comment by vmihailenco** [comment]
In v2.0.0-rc.1 you can add this to your Uptrace config:

```
##
## Initial data to create on first startup.
##
seed_data:
  users:
    - name: Admin
      key: user1 # Unique user key for links below
      email: admin@localhost.xxx
      password: admin
      auth_tokens: ['user1_secret']

  orgs:
    - name: Org1
      key: org1 # Unique org key for links below

  org_users:
    - org: org1 # Link to org key
      user: user1 # Link to user key
      role: owner

  projects:
    - name: Project1
      key: project1 # Unique project key for links below
      org: org1 # Link to org key
      tokens: [project1_secret]

  project_users:
    - project: project1 # Link to project key
      user: user1 # Link to user key
      perm_level: admin
```

The only catch is that the database will be seeded once . No updates. We plan to address this in later versions.
